sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - stable
  - 5
  - 4
before_install:
  - npm install -g npm@latest
before_script:
  - npm prune
after_success:
  - npm run coveralls
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
